all: listic_tests.o runall.o unity.o unity_fixture.o

listic_tests.o:
	gcc -c listic_tests.c -o ../build/listic_tests.o

runall.o:
	gcc -c runall.c -o ../build/runall.o

unity.o:
	gcc -c ../../unity/unity.c -o ../build/unity.o

unity_fixture.o:
	gcc -c ../../unity/unity_fixture.c -o ../build/unity_fixture.o
